data_link: "https://drive.google.com/uc?export=download&amp&id=13xzPp_HUshdsy1ia1ya4Gn8lqpBw8VLX&amp&confirm=t&amp&uuid=d9042302-2229-4102-8efc-a03970cdabb8"

paths2save:
  data: "data"
  exploration: "exploration_plots"
  models: "models"

model:
  model: "test_model"
  name: "test_model"

data_fuatures_in_use:
    date: "date"
    close: "close"
    open: "open"
    high: "high"
    low: "low"
    labels: "labels"

data_engineering:
  fill_method: "linear"  # polynomial or linear
  poly_order: 2

label_tolerance:
  tolerance: 0.0001

scaling_method: "asdaf"
min_max_scaler_range: ""

general_params:
  seed: 7

BiLSTM:
  General_params:
    window_length: 7

  Hyper_params:
    lstm_units_min: 10
    lstm_units_max: 12
    lstm_units_step: 2
    dense_units_min: 10
    dense_units_max: 12
    dense_units_step: 2
    lr_min: 0.001
    lr_max: 0.01
    lr_step: 2
    drop_out_min: 0.1
    drop_out_max: 0.2
    drop_out_step: 1






